#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# gentle-ai OPSX — Patch Script
# Applies OPSX workflow on top of an existing gentle-ai installation.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/JuanCruzRobledo/Gentle-Ai-Stack-SDD-OPSX/main/scripts/install-opsx.sh | bash
#
# Requires: git (NO Go required)
# Pre-requisite: gentle-ai must be already installed and synced
# ============================================================================

GITHUB_OWNER="JuanCruzRobledo"
GITHUB_REPO="Gentle-Ai-Stack-SDD-OPSX"
HOME_DIR="$HOME"

# Skills to patch (directory names in internal/assets/skills/)
SKILLS=(sdd-init sdd-apply sdd-verify sdd-explore sdd-propose sdd-spec sdd-design sdd-tasks sdd-archive sdd-onboard)

# ============================================================================
# Color support
# ============================================================================

setup_colors() {
    if [ -t 1 ] && [ "${TERM:-}" != "dumb" ]; then
        RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
        BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'
        DIM='\033[2m'; NC='\033[0m'
    else
        RED='' GREEN='' YELLOW='' BLUE='' CYAN='' BOLD='' DIM='' NC=''
    fi
}

info()    { echo -e "${BLUE}[info]${NC}    $*"; }
success() { echo -e "${GREEN}[ok]${NC}      $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC}    $*"; }
fatal()   { echo -e "${RED}[error]${NC}   $*" >&2; exit 1; }
step()    { echo -e "\n${CYAN}${BOLD}==>${NC} ${BOLD}$*${NC}"; }

print_banner() {
    echo ""
    echo -e "${CYAN}${BOLD}"
    echo "   ____            _   _              _    ___ "
    echo "  / ___| ___ _ __ | |_| | ___        / \  |_ _|"
    echo " | |  _ / _ \ '_ \| __| |/ _ \_____ / _ \  | | "
    echo " | |_| |  __/ | | | |_| |  __/_____/ ___ \ | | "
    echo "  \____|\___|_| |_|\__|_|\___|    /_/   \_\___|"
    echo -e "${NC}"
    echo -e "  ${DIM}OPSX Patch — Fluid workflow powered by OpenSpec CLI${NC}"
    echo ""
}

# ============================================================================
# Prerequisites
# ============================================================================

check_prerequisites() {
    step "Checking prerequisites"

    if ! command -v git &>/dev/null; then
        fatal "git is required. Install it and try again."
    fi

    # Check that at least one agent is configured
    local found=false
    for dir in "$HOME_DIR/.claude" "$HOME_DIR/.config/opencode" "$HOME_DIR/.cursor" "$HOME_DIR/.gemini" "$HOME_DIR/.codex" "$HOME_DIR/.codeium/windsurf"; do
        if [ -d "$dir" ]; then
            found=true
            break
        fi
    done

    if [ "$found" = false ]; then
        fatal "No AI agent configuration found. Install gentle-ai first: https://github.com/Gentleman-Programming/gentle-ai"
    fi

    success "Prerequisites OK"
}

# ============================================================================
# Clone fork
# ============================================================================

clone_fork() {
    step "Downloading OPSX patch files"

    TMPDIR="$(mktemp -d)"
    trap '[ -n "${TMPDIR:-}" ] && rm -rf "$TMPDIR"' EXIT

    git clone --depth 1 "https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git" "$TMPDIR/repo" 2>&1 | tail -1
    ASSETS="$TMPDIR/repo/internal/assets"
    success "Downloaded"
}

# ============================================================================
# Clean legacy commands
# ============================================================================

clean_legacy() {
    step "Cleaning legacy SDD commands"

    local cleaned=false

    # OpenCode commands
    if ls "$HOME_DIR/.config/opencode/commands/sdd-"*.md &>/dev/null 2>&1; then
        rm -f "$HOME_DIR/.config/opencode/commands/sdd-"*.md
        cleaned=true
    fi

    # OpenCode JSON (will be regenerated by next official sync, but orchestrator will be patched)
    if [ -f "$HOME_DIR/.config/opencode/opencode.json" ]; then
        rm -f "$HOME_DIR/.config/opencode/opencode.json"
        cleaned=true
    fi

    if [ "$cleaned" = true ]; then
        success "Legacy commands removed"
    else
        success "No legacy commands found"
    fi
}

# ============================================================================
# Patch skills (shared across all agents)
# ============================================================================

patch_skills() {
    step "Patching skills to OPSX"

    local skill_dirs=(
        "$HOME_DIR/.claude/skills"
        "$HOME_DIR/.config/opencode/skills"
        "$HOME_DIR/.cursor/skills"
        "$HOME_DIR/.gemini/skills"
        "$HOME_DIR/.codex/skills"
        "$HOME_DIR/.codeium/windsurf/skills"
        "$HOME_DIR/.gemini/antigravity/skills"
    )

    local patched=0

    for skill_dir in "${skill_dirs[@]}"; do
        if [ ! -d "$skill_dir" ]; then
            continue
        fi

        for skill in "${SKILLS[@]}"; do
            local target="$skill_dir/$skill/SKILL.md"
            local source="$ASSETS/skills/$skill/SKILL.md"

            if [ -f "$target" ] && [ -f "$source" ]; then
                cp "$source" "$target"
                patched=$((patched + 1))
            fi
        done
    done

    success "Patched $patched skill files"
}

# ============================================================================
# Patch Claude Code orchestrator (markdown sections)
# ============================================================================

patch_claude() {
    local claude_md="$HOME_DIR/.claude/CLAUDE.md"

    if [ ! -f "$claude_md" ]; then
        return
    fi

    step "Patching Claude Code orchestrator"

    local opsx_content
    opsx_content="$(cat "$ASSETS/claude/sdd-orchestrator.md")"

    local open_marker="<!-- gentle-ai:sdd-orchestrator -->"
    local close_marker="<!-- /gentle-ai:sdd-orchestrator -->"

    if grep -q "$open_marker" "$claude_md"; then
        # Replace content between markers
        local tmpfile="$TMPDIR/claude_md_patched"

        awk -v open="$open_marker" -v close="$close_marker" -v content="$opsx_content" '
        BEGIN { skip=0; printed=0 }
        $0 == open {
            print $0
            print content
            skip=1
            printed=1
            next
        }
        $0 == close {
            print $0
            skip=0
            next
        }
        skip==0 { print }
        ' "$claude_md" > "$tmpfile"

        cp "$tmpfile" "$claude_md"
        success "Claude Code orchestrator updated (replaced section)"
    else
        # Append new section
        {
            echo ""
            echo "$open_marker"
            echo "$opsx_content"
            echo "$close_marker"
        } >> "$claude_md"
        success "Claude Code orchestrator added (new section)"
    fi
}

# ============================================================================
# Patch agents using FileReplace/AppendToFile strategy
# ============================================================================

patch_file_agents() {
    # agent_name -> (system_prompt_file, orchestrator_asset, strategy)
    local -A agents=(
        ["opencode"]="$HOME_DIR/.config/opencode/AGENTS.md|generic/sdd-orchestrator.md|replace"
        ["cursor"]="$HOME_DIR/.cursor/rules/gentle-ai.mdc|cursor/sdd-orchestrator.md|replace"
        ["gemini"]="$HOME_DIR/.gemini/GEMINI.md|gemini/sdd-orchestrator.md|replace"
        ["codex"]="$HOME_DIR/.codex/agents.md|codex/sdd-orchestrator.md|replace"
        ["windsurf"]="$HOME_DIR/.codeium/windsurf/memories/global_rules.md|windsurf/sdd-orchestrator.md|append"
    )

    for agent in "${!agents[@]}"; do
        IFS='|' read -r prompt_file asset_path strategy <<< "${agents[$agent]}"

        if [ ! -f "$prompt_file" ]; then
            continue
        fi

        local opsx_content
        opsx_content="$(cat "$ASSETS/$asset_path")"

        local open_marker="<!-- gentle-ai:sdd-orchestrator -->"
        local close_marker="<!-- /gentle-ai:sdd-orchestrator -->"

        if grep -q "$open_marker" "$prompt_file"; then
            # Replace between markers
            local tmpfile="$TMPDIR/${agent}_patched"

            awk -v open="$open_marker" -v close="$close_marker" -v content="$opsx_content" '
            BEGIN { skip=0 }
            $0 == open {
                print $0
                print content
                skip=1
                next
            }
            $0 == close {
                print $0
                skip=0
                next
            }
            skip==0 { print }
            ' "$prompt_file" > "$tmpfile"

            cp "$tmpfile" "$prompt_file"
            info "  $agent: orchestrator replaced"
        elif [ "$strategy" = "append" ]; then
            {
                echo ""
                echo "$open_marker"
                echo "$opsx_content"
                echo "$close_marker"
            } >> "$prompt_file"
            info "  $agent: orchestrator appended"
        else
            {
                echo "$open_marker"
                echo "$opsx_content"
                echo "$close_marker"
            } > "$prompt_file"
            info "  $agent: orchestrator written"
        fi
    done
}

# ============================================================================
# Patch OpenCode commands
# ============================================================================

patch_opencode_commands() {
    local commands_dir="$HOME_DIR/.config/opencode/commands"

    if [ ! -d "$commands_dir" ]; then
        return
    fi

    for cmd_file in "$ASSETS/opencode/commands/"*.md; do
        local filename
        filename="$(basename "$cmd_file")"
        cp "$cmd_file" "$commands_dir/$filename"
    done

    info "  opencode: OPSX commands installed"
}

# ============================================================================
# Summary
# ============================================================================

print_summary() {
    step "Patching agent orchestrators"
    patch_file_agents
    patch_opencode_commands

    echo ""
    echo -e "${GREEN}${BOLD}OPSX patch applied successfully!${NC}"
    echo ""
    echo -e "${BOLD}What was patched:${NC}"
    echo -e "  - Skills rewritten to use ${CYAN}openspec CLI${NC}"
    echo -e "  - Orchestrator instructions updated to ${CYAN}OPSX workflow${NC}"
    echo -e "  - Legacy SDD commands removed"
    echo ""
    echo -e "${BOLD}OPSX Commands (in your AI agent):${NC}"
    echo -e "  ${CYAN}/opsx:explore${NC}  — Think through ideas before committing"
    echo -e "  ${CYAN}/opsx:propose${NC}  — Create a change with all artifacts"
    echo -e "  ${CYAN}/opsx:apply${NC}    — Implement tasks from the change"
    echo -e "  ${CYAN}/opsx:archive${NC}  — Sync specs and close the change"
    echo ""
    echo -e "${DIM}Restart your AI agent for changes to take effect.${NC}"
    echo -e "${DIM}Docs: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}${NC}"
    echo ""
}

# ============================================================================
# Main
# ============================================================================

main() {
    setup_colors
    print_banner
    check_prerequisites
    clone_fork
    clean_legacy
    patch_skills
    patch_claude
    print_summary
}

main "$@"
